const cardItems = [
	{
		id: 1,
		title: "Arbres Numériques",
		image:"../public/arbre-numerique.png",
		content:"Des structures arborescentes interactives équipées d'écrans LED organiques qui changent de couleur et d'affichage en réponse aux conditions météorologiques, créant ainsi une toile vivante et dynamique dans le paysage urbain.",
		scope: "ville",
	},
	{
		id: 2,
		title: "Bougie Virtuelle",
		image:"../public/bougie-virtuelle.png",
		content:"Une bougie connectée qui crée des motifs lumineux et des arômes changeants, évoquant différentes ambiances pour accompagner des moments de détente.",
		scope: "quotidien",
	}, 	
	{
		id: 3,	
		title: "Bibliothèque Émotionnelle",
		image:"../public/bibliotheque-emotionnelle.png",
		content:"Une bibliothèque interactive qui suggère des livres en fonction de l'humeur de l'utilisateur, offrant une expérience de lecture adaptée à chaque état d'esprit.",
		scope: "quotidien",
	},
	{
		id: 4,
		title: "Cascades de Pluie",
		image:"../public/cascades-de-pluie.png",
		content:"Des dispositifs installés le long des façades des bâtiments qui captent l'eau de pluie et la redistribuent en fines cascades colorées, ajoutant une dimension artistique aux journées pluvieuses tout en encourageant la récupération d'eau.",
		scope: "ville",
	}, 	
	{
		id: 5,
		title: "Coffret à Rêves",
		image:"../public/dream-box.png",
		content:"Un coffret interactif qui capture et visualise les rêves de l'utilisateur sous forme d'art visuel, offrant une expérience poétique et onirique au réveil.",
		scope: "quotidien",
	},
	{
		id: 6,
		title: "Fenêtre Virtuelle",
		image:"../public/fenetre-virtuelle.png",
		content:"Un écran intelligent intégré à une fenêtre qui affiche des vues virtuelles de paysages apaisants, transformant n'importe quelle pièce en un lieu de détente.",
		scope: "quotidien",
	},
	{
		id: 7,
		title: "Fontaines Musicales",
		image:"../public/fontaine-musicale.png",
		content:"Des fontaines publiques équipées de capteurs de mouvement et de musique intégrée, créant des spectacles aquatiques synchronisés avec des compositions musicales en temps réel, offrant ainsi une expérience sensorielle unique.",
		scope: "ville",
	}, 
	{
		id: 8,
		title: "Globe Holographique ",
		image:"../public/interactive-globe.png",
		content:"Un globe interactif affichant des informations en temps réel, telles que la météo, les événements mondiaux et des paysages holographiques à explorer.",
		scope: "quotidien",
	},
	{
		id: 9,
		title: "Miroir de Confiance",
		image: "../public/miroir-confiance.png",
		content: "Un miroir intelligent équipé de fonctionnalités de réalité augmentée pour encourager la confiance en soi en affichant des affirmations positives et des compliments personnalisés.",
		scope: "quotidien",
	},
	{
		id: 10,
		title: "Parapluie Lumineux",
		image:"../public/parapluie-lumineux.png",
		content:"Des parapluies dotés de fibres optiques lumineuses qui illuminent les rues pendant les jours de pluie, ajoutant une touche de couleur et de sécurité tout en transformant les averses en moments enchanteurs.",
		scope: "ville",
	}, 	
	{
		id: 11,
		title: "Pavés Énergétiques",
		image:"../public/paves-energetiques.png",
		content:"Des pavés de rue intelligents qui convertissent l'énergie cinétique des pas des passants en électricité, alimentant ainsi des lampadaires LED le long des trottoirs, créant une illumination durable et éco-friendly.",
		scope: "ville",
	}, 	
	{ 
		id: 12,
		title: "Plante Connectée",
		image:"../public/plante-connectee.png",
		content:"Un pot de fleurs intelligent qui réagit à l'humeur de son propriétaire en changeant de couleur ou en émettant des fragrances apaisantes, créant une expérience sensorielle immersive.",
		scope: "quotidien",
	},
	{
		id: 13,
		title: "Poteaux Connectés",
		image:"../public/poteaux-connectes.png",
		content:"Des poteaux d'éclairage public équipés de capteurs intelligents qui ajustent automatiquement l'intensité lumineuse en fonction de la densité de la population, créant des rues éclairées de manière optimale et économe en énergie.",
		scope: "ville",
	},
	{
		id: 14,
		title: "Sculpture Sonore",
		image:"../public/sound-sculpture.png",
		content:"Une sculpture artistique équipée de capteurs tactiles et sonores, permettant aux utilisateurs de créer des compositions musicales en interagissant avec elle.",
		scope: "quotidien",
	},
	{
		id: 15,
		title: "Tableau d'Ambiance",
		image: "../public/tableau-interactif.png",
		content: "Un tableau mural qui s'adapte aux émotions de la journée, affichant des animations apaisantes, inspirantes ou dynamiques en fonction de l'ambiance souhaitée.",
		scope: "quotidien",
	},       
  ];

export default cardItems;